#! /bin/sh

bspc config border_width        2
bspc config window_gap         12
bspc config top_padding        10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# focus options:
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false
bspc config focus_by_distance true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc desktop ^1 -t floating=on
bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

